import {
  CheckSquare,
  Terminal,
  Database,
  CodeSquare,
  Globe,
  Activity,
  Monitor,
  Layout,
  PenTool,
  Smartphone,
  Code,
  Server,
  Package,
  Cloud,
  ListChecks,
} from 'lucide-react';

export const CATEGORY_ICONS: Record<string, React.ReactNode> = {
  agileMethodologies: <ListChecks className="h-5 w-5" />,
  backendTechnologies: <Server className="h-5 w-5" />,
  build: <Terminal className="h-5 w-5" />,
  communication: <Globe className="h-5 w-5" />,
  core: <Code className="h-5 w-5" />,
  databases: <Database className="h-5 w-5" />,
  devops: <Cloud className="h-5 w-5" />,
  ecommerceCms: <Layout className="h-5 w-5" />,
  frameworks: <Layout className="h-5 w-5" />,
  mobile: <Smartphone className="h-5 w-5" />,
  monitoring: <Activity className="h-5 w-5" />,
  operatingSystems: <Monitor className="h-5 w-5" />,
  packageManagers: <Package className="h-5 w-5" />,
  programmingLanguages: <CodeSquare className="h-5 w-5" />,
  projectManagement: <CheckSquare className="h-5 w-5" />,
  stateManagement: <Activity className="h-5 w-5" />,
  testing: <CheckSquare className="h-5 w-5" />,
  ui: <PenTool className="h-5 w-5" />,
};
