import { Cloud, GitBranch, Monitor, Terminal } from 'lucide-react';

import {
  SiAmazon,
  SiAngular,
  SiApple,
  SiBabel,
  SiBitbucket,
  SiBootstrap,
  SiBower,
  SiChakraui,
  SiCss3,
  SiCsswizardry,
  SiCypress,
  SiDatadog,
  SiDocker,
  SiElasticsearch,
  SiElixir,
  SiFirebase,
  SiGit,
  SiGithub,
  SiGo,
  SiGooglecloud,
  SiGraphql,
  SiGrunt,
  SiGulp,
  SiHtml5,
  SiIonic,
  SiJavascript,
  SiJest,
  SiJira,
  SiJquery,
  SiLess,
  SiLinux,
  SiMongodb,
  SiMysql,
  SiNewrelic,
  SiNextdotjs,
  SiNgrx,
  SiNodedotjs,
  SiNpm,
  SiPnpm,
  SiPostgresql,
  SiProtractor,
  SiReact,
  SiRedux,
  SiSass,
  SiSentry,
  SiShopify,
  SiSocketdotio,
  SiSqlite,
  SiStyledcomponents,
  SiSvelte,
  SiSwift,
  SiTailwindcss,
  SiTrello,
  SiTypescript,
  SiVercel,
  SiVite,
  SiVuedotjs,
  SiWebpack,
  SiYarn,
} from 'react-icons/si';

import {
  KanbanIcon,
  KarmaIcon,
  PythonIcon,
  RxJSIcon,
  ScrumIcon,
  ZustandIcon,
} from '@/components/icons';

import { Skill } from '../types';

export const SKILLS: Skill[] = [
  {
    id: 'angular-material',
    name: 'Angular Material',
    icon: <SiAngular className="h-5 w-5" />,
    level: 5,
    color: 'text-angular-material',
    isFavorite: true,
  },
  {
    id: 'azure-devops',
    name: 'Azure DevOps',
    icon: <Cloud className="h-5 w-5" />,
    level: 2,
    color: 'text-azure',
    isFavorite: true,
  },
  {
    id: 'css-modules',
    name: 'CSS Modules',
    icon: <SiCsswizardry className="h-5 w-5" />,
    level: 5,
    color: 'text-css-modules',
    isFavorite: false,
  },
  {
    id: 'firebase-realtime-db',
    name: 'Firebase Realtime DB',
    icon: <SiFirebase className="h-5 w-5" />,
    level: 3,
    color: 'text-firebase',
    isFavorite: false,
  },
  {
    id: 'google-cloud',
    name: 'Google Cloud',
    icon: <SiGooglecloud className="h-5 w-5" />,
    level: 2,
    color: 'text-googlecloud',
    isFavorite: false,
  },
  {
    id: 'new-relic',
    name: 'New Relic',
    icon: <SiNewrelic className="h-5 w-5" />,
    level: 2,
    color: 'text-new-relic',
    isFavorite: false,
  },
  {
    id: 'next-js',
    name: 'Next.js',
    icon: <SiNextdotjs className="h-5 w-5" />,
    level: 4,
    color: 'text-nextjs dark:text-nextjs-light',
    isFavorite: true,
  },
  {
    id: 'react-testing-library',
    name: 'React Testing Library',
    icon: <SiReact className="h-5 w-5" />,
    level: 4,
    color: 'text-react-testing-library',
    isFavorite: false,
  },
  {
    id: 'rest-api',
    name: 'REST API',
    icon: null,
    level: 4,
    color: null,
    isFavorite: true,
  },
  {
    id: 'socket-io',
    name: 'Socket.io',
    icon: <SiSocketdotio className="h-5 w-5" />,
    level: 4,
    color: 'text-socketio dark:text-socketio-light',
    isFavorite: false,
  },
  {
    id: 'styled-components',
    name: 'Styled Components',
    icon: <SiStyledcomponents className="h-5 w-5" />,
    level: 4,
    color: 'text-styled-components',
    isFavorite: false,
  },
  {
    id: 'angular',
    name: 'Angular',
    icon: <SiAngular className="h-5 w-5" />,
    level: 5,
    color: 'text-angular',
    isFavorite: false,
  },
  {
    id: 'angular-js',
    name: 'AngularJS',
    icon: <SiAngular className="h-5 w-5" />,
    level: 5,
    color: 'text-angularjs',
    isFavorite: false,
  },
  {
    id: 'aws',
    name: 'AWS',
    icon: <SiAmazon className="h-5 w-5" />,
    level: 3,
    color: 'text-aws',
    isFavorite: false,
  },
  {
    id: 'babel',
    name: 'Babel',
    icon: <SiBabel className="h-5 w-5" />,
    level: 5,
    color: 'text-babel',
    isFavorite: true,
  },
  {
    id: 'bitbucket',
    name: 'Bitbucket',
    icon: <SiBitbucket className="h-5 w-5" />,
    level: 4,
    color: 'text-bitbucket',
    isFavorite: false,
  },
  {
    id: 'bootstrap',
    name: 'Bootstrap',
    icon: <SiBootstrap className="h-5 w-5" />,
    level: 4,
    color: 'text-bootstrap',
    isFavorite: false,
  },
  {
    id: 'bower',
    name: 'Bower',
    icon: <SiBower className="h-5 w-5" />,
    level: 4,
    color: 'text-bower',
    isFavorite: false,
  },
  {
    id: 'chakra-ui',
    name: 'ChakraUI',
    icon: <SiChakraui className="h-5 w-5" />,
    level: 5,
    color: 'text-chakraui',
    isFavorite: true,
  },
  {
    id: 'css3',
    name: 'CSS3',
    icon: <SiCss3 className="h-5 w-5" />,
    level: 5,
    color: 'text-css3',
    isFavorite: true,
  },
  {
    id: 'cypress',
    name: 'Cypress',
    icon: <SiCypress className="h-5 w-5" />,
    level: 4,
    color: 'text-cypress dark:text-cypress-light',
    isFavorite: true,
  },
  {
    id: 'datadog',
    name: 'Datadog',
    icon: <SiDatadog className="h-5 w-5" />,
    level: 2,
    color: 'text-datadog',
    isFavorite: false,
  },
  {
    id: 'docker',
    name: 'Docker',
    icon: <SiDocker className="h-5 w-5" />,
    level: 3,
    color: 'text-docker',
    isFavorite: true,
  },
  {
    id: 'elasticsearch',
    name: 'Elasticsearch',
    icon: <SiElasticsearch className="h-5 w-5" />,
    level: 3,
    color: 'text-destructive',
    isFavorite: false,
  },
  {
    id: 'elixir',
    name: 'Elixir',
    icon: <SiElixir className="h-5 w-5" />,
    level: 2,
    color: 'text-elixir',
    isFavorite: false,
  },
  {
    id: 'firebase',
    name: 'Firebase',
    icon: <SiFirebase className="h-5 w-5" />,
    level: 4,
    color: 'text-firebase',
    isFavorite: false,
  },
  {
    id: 'git',
    name: 'Git',
    icon: <SiGit className="h-5 w-5" />,
    level: 5,
    color: 'text-git',
    isFavorite: true,
  },
  {
    id: 'git-flow',
    name: 'Git Flow',
    icon: <GitBranch className="h-5 w-5" />,
    level: 5,
    color: 'text-git',
    isFavorite: false,
  },
  {
    id: 'github',
    name: 'GitHub',
    icon: <SiGithub className="h-5 w-5" />,
    level: 5,
    color: 'text-github dark:text-github-light',
    isFavorite: true,
  },
  {
    id: 'go',
    name: 'Go',
    icon: <SiGo className="h-5 w-5" />,
    level: 1,
    color: 'text-go',
    isFavorite: false,
  },
  {
    id: 'graphql',
    name: 'GraphQL',
    icon: <SiGraphql className="h-5 w-5" />,
    level: 2,
    color: 'text-graphql',
    isFavorite: true,
  },
  {
    id: 'grunt',
    name: 'Grunt',
    icon: <SiGrunt className="h-5 w-5" />,
    level: 3,
    color: 'text-grunt',
    isFavorite: false,
  },
  {
    id: 'gulp',
    name: 'Gulp',
    icon: <SiGulp className="h-5 w-5" />,
    level: 4,
    color: 'text-gulp',
    isFavorite: false,
  },
  {
    id: 'html5',
    name: 'HTML5',
    icon: <SiHtml5 className="h-5 w-5" />,
    level: 5,
    color: 'text-html5',
    isFavorite: true,
  },
  {
    id: 'ionic',
    name: 'Ionic',
    icon: <SiIonic className="h-5 w-5" />,
    level: 2,
    color: 'text-ionic',
    isFavorite: false,
  },
  {
    id: 'javascript',
    name: 'JavaScript',
    icon: <SiJavascript className="h-5 w-5" />,
    level: 5,
    color: 'text-javascript',
    isFavorite: true,
  },
  {
    id: 'jest',
    name: 'Jest',
    icon: <SiJest className="h-5 w-5" />,
    level: 5,
    color: 'text-jest',
    isFavorite: true,
  },
  {
    id: 'jira',
    name: 'Jira',
    icon: <SiJira className="h-5 w-5" />,
    level: 5,
    color: 'text-jira',
    isFavorite: true,
  },
  {
    id: 'jquery',
    name: 'jQuery',
    icon: <SiJquery className="h-5 w-5" />,
    level: 4,
    color: 'text-jquery',
    isFavorite: false,
  },
  {
    id: 'kanban',
    name: 'Kanban',
    icon: <KanbanIcon className="h-5 w-5" />,
    level: 4,
    color: 'text-purple-500 dark:text-purple-400',
    isFavorite: false,
  },
  {
    id: 'karma',
    name: 'Karma',
    icon: <KarmaIcon className="h-5 w-5" />,
    level: 4,
    color: 'text-karma',
    isFavorite: false,
  },
  {
    id: 'less',
    name: 'Less',
    icon: <SiLess className="h-5 w-5" />,
    level: 4,
    color: 'text-less dark:text-less-light',
    isFavorite: false,
  },
  {
    id: 'linux',
    name: 'Linux',
    icon: <SiLinux className="h-5 w-5" />,
    level: 5,
    color: 'text-linux dark:text-linux-light',
    isFavorite: true,
  },
  {
    id: 'mac',
    name: 'Mac',
    icon: <SiApple className="h-5 w-5" />,
    level: 5,
    color: 'text-mac',
    isFavorite: true,
  },
  {
    id: 'mongodb',
    name: 'MongoDB',
    icon: <SiMongodb className="h-5 w-5" />,
    level: 3,
    color: 'text-mongodb',
    isFavorite: false,
  },
  {
    id: 'mysql',
    name: 'MySQL',
    icon: <SiMysql className="h-5 w-5" />,
    level: 4,
    color: 'text-mysql',
    isFavorite: true,
  },
  {
    id: 'ngrx',
    name: 'NGRX',
    icon: <SiNgrx className="h-5 w-5" />,
    level: 3,
    color: 'text-ngrx',
    isFavorite: false,
  },
  {
    id: 'node-js',
    name: 'Node.js',
    icon: <SiNodedotjs className="h-5 w-5" />,
    level: 4,
    color: 'text-nodejs',
    isFavorite: true,
  },
  {
    id: 'npm',
    name: 'NPM',
    icon: <SiNpm className="h-5 w-5" />,
    level: 5,
    color: 'text-npm',
    isFavorite: true,
  },
  {
    id: 'pnpm',
    name: 'PNPM',
    icon: <SiPnpm className="h-5 w-5" />,
    level: 5,
    color: 'text-pnpm',
    isFavorite: true,
  },
  {
    id: 'postgre-sql',
    name: 'PostgreSQL',
    icon: <SiPostgresql className="h-5 w-5" />,
    level: 2,
    color: 'text-postgres',
    isFavorite: false,
  },
  {
    id: 'protractor',
    name: 'Protractor',
    icon: <SiProtractor className="h-5 w-5" />,
    level: 4,
    color: 'text-protractor',
    isFavorite: false,
  },
  {
    id: 'python',
    name: 'Python',
    icon: <PythonIcon className="h-5 w-5" />,
    level: 3,
    color: 'text-python',
    isFavorite: false,
  },
  {
    id: 'react-js',
    name: 'ReactJS',
    icon: <SiReact className="h-5 w-5" />,
    level: 5,
    color: 'text-reactjs',
    isFavorite: true,
  },
  {
    id: 'redux',
    name: 'Redux',
    icon: <SiRedux className="h-5 w-5" />,
    level: 4,
    color: 'text-redux',
    isFavorite: false,
  },
  {
    id: 'rxjs',
    name: 'RxJS',
    icon: <RxJSIcon className="h-5 w-5" />,
    level: 4,
    color: 'text-rxjs',
    isFavorite: false,
  },
  {
    id: 'sass',
    name: 'Sass',
    icon: <SiSass className="h-5 w-5" />,
    level: 5,
    color: 'text-sass',
    isFavorite: true,
  },
  {
    id: 'scrum',
    name: 'Scrum',
    icon: <ScrumIcon className="h-5 w-5" />,
    level: 5,
    color: 'text-blue-500 dark:text-blue-400',
    isFavorite: true,
  },
  {
    id: 'sentry',
    name: 'Sentry',
    icon: <SiSentry className="h-5 w-5" />,
    level: 4,
    color: 'text-sentry dark:text-sentry-light',
    isFavorite: true,
  },
  {
    id: 'shellscript',
    name: 'Shell Script',
    icon: <Terminal className="h-5 w-5" />,
    level: 3,
    color: 'text-shellscript dark:text-shellscript-light',
    isFavorite: false,
  },
  {
    id: 'shopify',
    name: 'Shopify',
    icon: <SiShopify className="h-5 w-5" />,
    level: 3,
    color: 'text-shopify',
    isFavorite: false,
  },
  {
    id: 'sqlite',
    name: 'SQLite',
    icon: <SiSqlite className="h-5 w-5" />,
    level: 5,
    color: 'text-sqlite',
    isFavorite: true,
  },
  {
    id: 'svelte',
    name: 'Svelte',
    icon: <SiSvelte className="h-5 w-5" />,
    level: 2,
    color: 'text-svelte',
    isFavorite: false,
  },
  {
    id: 'swift',
    name: 'Swift',
    icon: <SiSwift className="h-5 w-5" />,
    level: 1,
    color: 'text-swift',
    isFavorite: true,
  },
  {
    id: 'tailwind',
    name: 'Tailwind',
    icon: <SiTailwindcss className="h-5 w-5" />,
    level: 5,
    color: 'text-tailwind',
    isFavorite: true,
  },
  {
    id: 'trello',
    name: 'Trello',
    icon: <SiTrello className="h-5 w-5" />,
    level: 4,
    color: 'text-trello',
    isFavorite: false,
  },
  {
    id: 'typescript',
    name: 'TypeScript',
    icon: <SiTypescript className="h-5 w-5" />,
    level: 5,
    color: 'text-typescript',
    isFavorite: true,
  },
  {
    id: 'vercel',
    name: 'Vercel',
    icon: <SiVercel className="h-5 w-5" />,
    level: 4,
    color: 'text-vercel dark:text-vercel-light',
    isFavorite: true,
  },
  {
    id: 'vite',
    name: 'Vite',
    icon: <SiVite className="h-5 w-5" />,
    level: 4,
    color: 'text-vite',
    isFavorite: true,
  },
  {
    id: 'vuejs',
    name: 'Vue.js',
    icon: <SiVuedotjs className="h-5 w-5" />,
    level: 3,
    color: 'text-vuejs',
    isFavorite: false,
  },
  {
    id: 'webpack',
    name: 'Webpack',
    icon: <SiWebpack className="h-5 w-5" />,
    level: 5,
    color: 'text-webpack',
    isFavorite: true,
  },
  {
    id: 'windows',
    name: 'Windows',
    icon: <Monitor className="h-5 w-5" />,
    level: 5,
    color: 'text-windows',
    isFavorite: false,
  },
  {
    id: 'yarn',
    name: 'Yarn',
    icon: <SiYarn className="h-5 w-5" />,
    level: 5,
    color: 'text-yarn',
    isFavorite: true,
  },
  {
    id: 'zustand',
    name: 'Zustand',
    icon: <ZustandIcon className="h-5 w-5" />,
    level: 4,
    color: 'text-zustand',
    isFavorite: true,
  },
];
